### ISSUE TITLE
ERD schema maken van Database

### ISSUE THREAD

**Issue by Verdonck-Lennert** [Agile-TestingTeam2/Project_winkellijst#21]
Klaarmaken van Entity Relation Diagram van de Database. Zo kunnen we aan klant laten zien wat we willen creëren.

**Comment by Verdonck-Lennert** [comment]
ERD nagekeken en goedgekeurd.

**Comment by bobbizamora** [comment]
bobbi says :  ERD Schema is geschreven en nagekeken
