### ISSUE TITLE
Inloggen: Uitzoeken rollen

### ISSUE THREAD

**Issue by Liedev** [Agile-TestingTeam2/Project_winkellijst#28]
Kijken welke rollen er zijn

**Comment by Verdonck-Lennert** [comment]
Ik ben aan het uitzoeken geweest en naar mijn mening zijn de rollen; "Gebruiker" & "Admin" de enige twee die er baat bij hebben om te gebruiken in dit programma. Wat denken jullie?

**Comment by Liedev** [comment]
Inderdaad maar ik zou dit ook aan de klant navragen of ze een admin willen of dat wij dit voor hun gaan oplossen.

**Comment by Verdonck-Lennert** [comment]
Oke, lijkt me inderdaad een goed idee.

**Comment by Verdonck-Lennert** [comment]
Focussen op enkel een gebruiker.
