### ISSUE TITLE
Vraag klant: Moet er een adminrol aanwezig zijn? Welke gegevens mag de gebruiker veranderen/verwijderen?

### ISSUE THREAD

**Issue by Liedev** [Agile-TestingTeam2/Project_winkellijst#33]

**Comment by bobbizamora** [comment]
Moet er een bepaalde huisstijl gehanteerd worden bij de opmaak van de applicatie? zo ja, kan u deze bezorgen?


Moet de applicatie een naam, logo, etc krijgen? We hebben de projectnaam Shop Match gekozen. Verklaring we matchen ons winkellijst aan een winkel

**Comment by Liedev** [comment]
Moet er een adminrol aanwezig zijn? Welke gegevens mag de gebruiker veranderen/verwijderen?

Moeten we het passwoord hashen of niet? Kostenplaatje... 
Klant inlichten over de mogelijkheden en wat er legaal moet gedaan zijn zie Item inloggen:Gdpr

**Comment by Verdonck-Lennert** [comment]
> 
> 
> Moet er een bepaalde huisstijl gehanteerd worden bij de opmaak van de applicatie? zo ja, kan u deze bezorgen?
> 
> Moet de applicatie een naam, logo, etc krijgen? We hebben de projectnaam Shop Match gekozen. Verklaring we matchen ons winkellijst aan een winkel

De vorige meeting met klant hebben we dacht ik te horen gekregen dat we ons eigen huisstijl mochten creëren. Dus ik denk niet dat dit nog eens gevraagd moet worden.

**Comment by Verdonck-Lennert** [comment]
> 
> 
> Moet er een adminrol aanwezig zijn? Welke gegevens mag de gebruiker veranderen/verwijderen?
> 
> Moeten we het passwoord hashen of niet? Kostenplaatje...
> Klant inlichten over de mogelijkheden en wat er legaal moet gedaan zijn zie Item inloggen:Gdpr

Ik ga tijdens de meeting ook vragen ivm met adminrol en het 'alter/delete'n van een gebruiker.
Alsook eens navragen om extra beveiliging in te schakelen door met hashcode te werken bij paswoorden en dergelijke meer.

**Comment by Liedev** [comment]
paswoorden moeten zoizo gehashed worden. Het gaat meer over persoonsgegevens hashen zoals mail => Zie erd
