### ISSUE TITLE
Inloggen: Schetsen aanpassen

### ISSUE THREAD

**Issue by Verdonck-Lennert** [Agile-TestingTeam2/Project_winkellijst#40]
Aanpassen van schetsen

**Comment by bobbizamora** [comment]
https://www.figma.com/proto/icFpTIQCsXvNKZfCBgsgLq/Shop-Match?node-id=1%3A5&viewport=60%2C242%2C0.4246314764022827&scaling=scale-down

**Comment by Verdonck-Lennert** [comment]
Hola, dit is nogsteeds een android/ios applicatie. We moeten Desktop schetsen hebben.
